export default [
    {
        name:'test_model',
        folder:'',
        file:'character.glb',
    },
    {
        name:'sphere',
        folder:'',
        file:'sphere.glb',
    },
    {
        name:'fences',
        folder:'',
        file:'fences.glb',
    },
    {
        name:'polygon',
        folder:'',
        file:'polygon.glb',
    },
    {
        name:'polygon_size',
        folder:'',
        file:'polygon_size.glb',
    },
    {
        name:'character',
        folder:'',
        file:'character.glb',
    },
    {
        name:'pyramid',
        folder:'',
        file:'pyramid.glb',
    },
    {
        name:'plant',
        folder:'',
        file:'plant.glb',
    },
    {
        name:'plant_1',
        folder:'',
        file:'plant_1.glb',
    },
    {
        name:'plant_2',
        folder:'',
        file:'plant_2.glb',
    }
]